/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#5a4225",
        "surface-container-highest": "#e0e3e6",
        "surface-bright": "#f7f9fc",
        "secondary-fixed-dim": "#ffb783",
        "error": "#ba1a1a",
        "surface-container-high": "#e6e8eb",
        "on-surface-variant": "#43474c",
        "on-secondary-fixed": "#301400",
        "primary-container": "#2c3e50",
        "tertiary-container": "#4e381c",
        "on-tertiary": "#ffffff",
        "tertiary": "#362308",
        "on-surface": "#191c1e",
        "surface-tint": "#4e6073",
        "on-primary-container": "#96a9be",
        "tertiary-fixed": "#ffddb7",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "inverse-primary": "#b5c8df",
        "outline": "#74777d",
        "surface-container-lowest": "#ffffff",
        "primary": "#162839",
        "on-tertiary-fixed": "#291802",
        "on-primary-fixed": "#091d2e",
        "on-primary-fixed-variant": "#36485b",
        "secondary-container": "#fc8f34",
        "surface-dim": "#d8dadd",
        "background": "#f7f9fc",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e6",
        "on-secondary-container": "#663100",
        "primary-fixed": "#d1e4fb",
        "on-secondary-fixed-variant": "#713700",
        "inverse-surface": "#2d3133",
        "on-tertiary-container": "#c1a17d",
        "tertiary-fixed-dim": "#e3c19b",
        "outline-variant": "#c4c6cd",
        "primary-fixed-dim": "#b5c8df",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container": "#eceef1",
        "inverse-on-surface": "#eff1f4",
        "secondary": "#944a00",
        "secondary-fixed": "#ffdcc5",
        "on-secondary": "#ffffff",
        "surface": "#f7f9fc",
        "surface-container-low": "#f2f4f7"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base_unit": "8px",
        "margin_page": "24px",
        "gutter": "16px",
        "topbar_height": "64px",
        "sidebar_width": "240px",
        "container_max": "1366px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "mono-data": ["JetBrains Mono"],
        "title-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"]
      },
      fontSize: {
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "mono-data": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "title-lg": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
